import pydot
from PIL import Image

graph = pydot.Dot(graph_type = 'digraph')

nandu = pydot.Node("Nandu Regmi", style = "filled")

skrishna = pydot.Node("Shree Krishna Regmi", style = "filled")
hangsini = pydot.Node("Hangsini Regmi", style = "filled")

chamu = pydot.Node("Chamu Regmi", style = "filled")
slal = pydot.Node("Shyamu Lal Regmi", style = "filled")

lure = pydot.Node("Lure Regmi", style = "filled")
jay = pydot.Node("Jay Lal Regmi", style = "filled")
ramchandra = pydot.Node("Ramchandra Regmi", style = "filled")

muse = pydot.Node("Muse Regmi", style = "filled")
sete = pydot.Node("Sete Regmi", style = "filled")
krishna = pydot.Node("Krishna Prasad Regmi", style = "filled")
tikaram = pydot.Node("Tikaram Sharma Regmi", style = "filled")
dev = pydot.Node("Dev Sharma Regmi", style = "filled")
bedu = pydot.Node("Bedu Regmi", style = "filled")
madhu = pydot.Node("Madhu Regmi", style = "filled")
shril = pydot.Node("Shril Regmi", style = "filled")




bishnudatta = pydot.Node("Bishnu Datta Regmi", style = "filled")
tanka = pydot.Node("Tanka Regmi", style = "filled")
durge = pydot.Node("Durga Regmi", style = "filled")
kaladhar = pydot.Node("Kaladhar Regmi", style = "filled")
diwakar = pydot.Node("Diwakar Regmi", style = "filled")

kul = pydot.Node("Kul Prasad Regmi", style = "filled")
indra = pydot.Node("Indra Prasad Regmi", style = "filled")
bhim = pydot.Node("Bhim Prasad Regmi", style = "filled")
sete1 = pydot.Node("Sete Regmi II", style = "filled")
arjun = pydot.Node("Arjun Regmi", style = "filled")
rudra = pydot.Node("Rudra Regmi", style = "filled")
rchandra = pydot.Node("Ramchandra Regmi II", style = "filled")
krishna1 = pydot.Node("Krishna Regmi", style = "filled")
dhurba = pydot.Node("Dhurba Regmi", style = "filled")
chiranjibi = pydot.Node("Chiranjibi Regmi", style = "filled")
liladhar = pydot.Node("Liladhar Regmi", style = "filled")

cholakanta = pydot.Node("Cholakanta Regmi", style = "filled")
gangi = pydot.Node("Ganga Poudel", style = "filled")
jagat = pydot.Node("Jagat Regmi", style = "filled")
radhika = pydot.Node("Radhika", style = "filled")
khagraj = pydot.Node("Khagraj Regmi", style = "filled")
jhalak = pydot.Node("Jhalak Regmi", style = "filled")
dinanath = pydot.Node("Dinanath Regmi", style = "filled")
prakash = pydot.Node("Prakash Regmi", style = "filled")
thuldidi = pydot.Node("Thuldidi", style = "filled")
babu = pydot.Node("Babu Ram Regmi", style = "filled")
puwa = pydot.Node("Puwa Syandidi", style = "filled")
hem = pydot.Node("Hem Raj Regmi", style = "filled")
devi = pydot.Node("Devi Poudel", style = "filled")
sita = pydot.Node("Sita Timalsina", style = "filled")
ganga = pydot.Node("Ganga Adhikari", style = "filled")
tika = pydot.Node("Tika Ram Regmi", style = "filled")
ram = pydot.Node("Ram Regmi", style = "filled")
lakshman = pydot.Node("Lakshman Regmi", style = "filled")
avi = pydot.Node("Avimanyu Regmi", style = "filled")
rashik = pydot.Node("Rashik Regmi", style = "filled")
rohan = pydot.Node("Rohan Regmi", style = "filled")
rashi = pydot.Node("Rashi Regmi", style = "filled")
anupam = pydot.Node("Anupam Regmi", style = "filled")
avishek = pydot.Node("Avishek Regmi", style = "filled")
aditya = pydot.Node("Aditya Regmi", style = "filled")
narayan = pydot.Node("Narayan Regmi", style = "filled")
ravi = pydot.Node("Ravi Regmi", style = "filled")
ajay = pydot.Node("Ajay Regmi", style = "filled")

milan = pydot.Node("Milan Regmi", style = "filled")
bidhan = pydot.Node("Bidhan Regmi", style = "filled")
bijay = pydot.Node("Bijay Regmi", style = "filled")
puru = pydot.Node("Purusottam Regmi", style = "filled")
manoj = pydot.Node("Manoj Regmi", style = "filled")
bodh = pydot.Node("Bodhraj Regmi", style = "filled")
ganesh = pydot.Node("Ganesh Regmi", style = "filled")
rabindra = pydot.Node("Rabindra Regmi", style = "filled")
dipak = pydot.Node("Dipak Regmi", style = "filled")
muna = pydot.Node("Muna", style = "filled")
rita = pydot.Node("Rita", style = "filled")
rama = pydot.Node("Rama", style = "filled")
bimala = pydot.Node("Bimala", style = "filled")
chhabi = pydot.Node("Chhabi Regmi", style = "filled")
kalpana = pydot.Node("Kalpana Regmi", style = "filled")
suman = pydot.Node("Suman Regmi", style = "filled")
subas = pydot.Node("Subas Regmi", style = "filled")
sudip = pydot.Node("Sudip Regmi", style = "filled")
suraj = pydot.Node("Suraj Regmi", style = "filled")
sudarshan = pydot.Node("Sudarshan Regmi", style = "filled")
nixon = pydot.Node("Nixon Regmi", style = "filled")
nirman = pydot.Node("Nirman Regmi", style = "filled")
nitish = pydot.Node("Nitish Regmi", style = "filled")


sammunat = pydot.Node("Sammunat Regmi", style = "filled")
samarpan = pydot.Node("Samarpan Regmi", style = "filled")
sangam = pydot.Node("Sangam Regmi", style = "filled")

graph.add_node(nandu)

graph.add_node(skrishna)
graph.add_node(hangsini)

graph.add_node(chamu)
graph.add_node(slal)

graph.add_node(lure)
graph.add_node(jay)
graph.add_node(ramchandra)

graph.add_node(muse)
graph.add_node(sete)
graph.add_node(krishna)
graph.add_node(tikaram)
graph.add_node(dev)
graph.add_node(bedu)
graph.add_node(madhu)
graph.add_node(shril)

graph.add_node(bishnudatta)
graph.add_node(tanka)
graph.add_node(durge)
graph.add_node(kaladhar)
graph.add_node(diwakar)

graph.add_node(kul)
graph.add_node(indra)
graph.add_node(bhim)
graph.add_node(sete1)
graph.add_node(arjun)
graph.add_node(rudra)
graph.add_node(rchandra)
graph.add_node(krishna1)
graph.add_node(dhurba)
graph.add_node(chiranjibi)
graph.add_node(liladhar)

graph.add_node(thuldidi)
graph.add_node(babu)
graph.add_node(puwa)
graph.add_node(hem)
graph.add_node(devi)
graph.add_node(sita)
graph.add_node(ganga)
graph.add_node(tika)
graph.add_node(cholakanta)
graph.add_node(gangi)
graph.add_node(jagat)
graph.add_node(radhika)
graph.add_node(khagraj)
graph.add_node(jhalak)
graph.add_node(dinanath)
graph.add_node(prakash)
graph.add_node(ram)
graph.add_node(lakshman)
graph.add_node(avi)
graph.add_node(rashik)
graph.add_node(rohan)
graph.add_node(rashi)
graph.add_node(anupam)
graph.add_node(avishek)
graph.add_node(aditya)
graph.add_node(narayan)
graph.add_node(ravi)
graph.add_node(ajay)

graph.add_node(manoj)
graph.add_node(bodh)
graph.add_node(ganesh)
graph.add_node(rabindra)
graph.add_node(dipak)
graph.add_node(muna)
graph.add_node(rita)
graph.add_node(rama)
graph.add_node(bimala)
graph.add_node(chhabi)
graph.add_node(kalpana)
graph.add_node(suman)
graph.add_node(subas)
graph.add_node(sudip)
graph.add_node(suraj)
graph.add_node(sudarshan)
graph.add_node(milan)
graph.add_node(bidhan)
graph.add_node(bijay)
graph.add_node(puru)
graph.add_node(nixon)
graph.add_node(nirman)
graph.add_node(nitish)

graph.add_node(samarpan)
graph.add_node(sammunat)
graph.add_node(sangam)

graph.add_edge(pydot.Edge(nandu, skrishna))
graph.add_edge(pydot.Edge(nandu, hangsini))

graph.add_edge(pydot.Edge(skrishna, chamu))
graph.add_edge(pydot.Edge(hangsini, slal))

graph.add_edge(pydot.Edge(chamu, lure))
graph.add_edge(pydot.Edge(chamu, jay))
graph.add_edge(pydot.Edge(slal, ramchandra))

graph.add_edge(pydot.Edge(lure, muse))
graph.add_edge(pydot.Edge(lure, sete))
graph.add_edge(pydot.Edge(jay, krishna))
graph.add_edge(pydot.Edge(jay, tikaram))
graph.add_edge(pydot.Edge(jay, dev))
graph.add_edge(pydot.Edge(ramchandra, bedu))
graph.add_edge(pydot.Edge(ramchandra, madhu))
graph.add_edge(pydot.Edge(ramchandra, shril))

graph.add_edge(pydot.Edge(dev, bishnudatta))
graph.add_edge(pydot.Edge(bedu, tanka))
graph.add_edge(pydot.Edge(madhu, durge))
graph.add_edge(pydot.Edge(shril, kaladhar))
graph.add_edge(pydot.Edge(shril, diwakar))

graph.add_edge(pydot.Edge(bishnudatta, kul))
graph.add_edge(pydot.Edge(bishnudatta, indra))
graph.add_edge(pydot.Edge(bishnudatta, bhim))
graph.add_edge(pydot.Edge(tanka, sete1))
graph.add_edge(pydot.Edge(durge, arjun))
graph.add_edge(pydot.Edge(durge, rudra))
graph.add_edge(pydot.Edge(durge, rchandra))
graph.add_edge(pydot.Edge(kaladhar, krishna1))
graph.add_edge(pydot.Edge(kaladhar, dhurba))
graph.add_edge(pydot.Edge(kaladhar, chiranjibi))
graph.add_edge(pydot.Edge(diwakar, liladhar))

graph.add_edge(pydot.Edge(kul, cholakanta))
graph.add_edge(pydot.Edge(kul, gangi))
graph.add_edge(pydot.Edge(kul, jagat))
graph.add_edge(pydot.Edge(kul, radhika))
graph.add_edge(pydot.Edge(indra, thuldidi))
graph.add_edge(pydot.Edge(indra, babu))
graph.add_edge(pydot.Edge(indra, puwa))
graph.add_edge(pydot.Edge(indra, hem))
graph.add_edge(pydot.Edge(indra, devi))
graph.add_edge(pydot.Edge(indra, sita))
graph.add_edge(pydot.Edge(indra, ganga))
graph.add_edge(pydot.Edge(indra, tika))
graph.add_edge(pydot.Edge(bhim, khagraj))
graph.add_edge(pydot.Edge(bhim, jhalak))
graph.add_edge(pydot.Edge(bhim, dinanath))
graph.add_edge(pydot.Edge(bhim, prakash))
graph.add_edge(pydot.Edge(sete1, ram))
graph.add_edge(pydot.Edge(sete1, lakshman))
graph.add_edge(pydot.Edge(arjun, avi))
graph.add_edge(pydot.Edge(rudra, rashik))
graph.add_edge(pydot.Edge(rudra, rohan))
graph.add_edge(pydot.Edge(rchandra, rashi))
graph.add_edge(pydot.Edge(dhurba, anupam))
graph.add_edge(pydot.Edge(dhurba, avishek))
graph.add_edge(pydot.Edge(chiranjibi, aditya))
graph.add_edge(pydot.Edge(liladhar, narayan))
graph.add_edge(pydot.Edge(liladhar, ravi))
graph.add_edge(pydot.Edge(liladhar, ajay))

graph.add_edge(pydot.Edge(babu, suman))
graph.add_edge(pydot.Edge(babu, subas))
graph.add_edge(pydot.Edge(hem, sudip))
graph.add_edge(pydot.Edge(tika, suraj))
graph.add_edge(pydot.Edge(tika, sudarshan))
graph.add_edge(pydot.Edge(cholakanta, milan))
graph.add_edge(pydot.Edge(cholakanta, bidhan))
graph.add_edge(pydot.Edge(jagat, bijay))
graph.add_edge(pydot.Edge(jagat, puru))
graph.add_edge(pydot.Edge(khagraj, manoj))
graph.add_edge(pydot.Edge(khagraj, bodh))
graph.add_edge(pydot.Edge(jhalak, ganesh))
graph.add_edge(pydot.Edge(jhalak, rabindra))
graph.add_edge(pydot.Edge(jhalak, dipak))
graph.add_edge(pydot.Edge(dinanath, muna))
graph.add_edge(pydot.Edge(dinanath, rita))
graph.add_edge(pydot.Edge(dinanath, rama))
graph.add_edge(pydot.Edge(prakash, bimala))
graph.add_edge(pydot.Edge(prakash, chhabi))
graph.add_edge(pydot.Edge(prakash, kalpana))
graph.add_edge(pydot.Edge(narayan, nixon))
graph.add_edge(pydot.Edge(ravi, nirman))
graph.add_edge(pydot.Edge(ajay, nitish))

graph.add_edge(pydot.Edge(suman, samarpan))
graph.add_edge(pydot.Edge(suman, sangam))
graph.add_edge(pydot.Edge(subas, sammunat))

graph.write_png('ancestry.png')

image = Image.open('ancestry.png')
image.show()














